### ISSUE TITLE
Move error messages to translation file

### ISSUE THREAD

**Issue by F3PiX** [rails-girls-summer-of-code/rgsoc-teams#878]
We have some custom error messages, for example here.
https://github.com/rails-girls-summer-of-code/rgsoc-teams/blob/db178cfe9d65c5c9f4c58e4bcf0d33148a221177/app/models/application_draft.rb#L141-L145

We want to move these custom error messages to the translation file `en.yml`. In [this commit ](https://github.com/rails-girls-summer-of-code/rgsoc-teams/pull/875/commits/acbd0b55a8a6661bd467c182a525af45d2a27e25)you can see how it is done, for an error message on the Todo model and its user attribute.

Collect all the error messages and put them into the translation file, at the right place.

**Comment by F3PiX** [comment]
@aSquare14 The best way to start is by selecting one of the issues with the 'beginner-friendly' label. Like this issue (or click on the yellow label, to see all issues with that label). Even if you are not a beginner at coding, they are suitable for first time contributors. 
Does this work for you?
  
After that, if you are looking for something more challenging, you can take a look at the issues labeled 'rgsoc18'. I wouldn't recommend all of them, but we can chat about that later. 

To learn more about projects: see https://railsgirlssummerofcode.org/guide/projects/ 
I don't know much more that what is in the guides ;-) , there is an email address in the guide for further inquiries.

**Comment by aSquare14** [comment]
Thank You !

**Comment by nileshgulia1** [comment]
Hey @F3PiX ,I would like to work on the  issue,will send a PR soon :)

**Comment by F3PiX** [comment]
Hi @nileshgulia1 Welcome at the Teams App!!! Great that you want to contribute. 👍  🎉 

@aSquare14 Are you currently working on this issue? Or can we pass it to @nileshgulia1 ?

@nileshgulia1 I'd hate to see you do double work for nothing, so please wait a few days until we know if @aSquare14 is working on this.

**Comment by aSquare14** [comment]
Nopes I'm not. He's free to work on it. All the best!

**Comment by F3PiX** [comment]
@nileshgulia1 All yours!!! 💃 

@aSquare14 Thanks for your swift reaction! Much appreciated.

**Comment by F3PiX** [comment]
@nileshgulia1 One more thing: be sure to _first_ pull in the latest changes - we just merged a huge PR - . Then create your branch, so that your commits are on top of the changes. 
This will save you a lot of merge conflicts later on. 
 
(Ask away if you need more explanation/help.)

**Comment by nileshgulia1** [comment]
hey @F3PiX ,need help translating error messages via  i18n.
For translating error messages in ```app/models/applicaton_draft```
``` ruby
def different_projects_required
    if project1 && project1 == project2
      errors.add(:projects, :must_not_be_selected_twice)
    end
  end

  def accepted_projects_required
    if projects.any? { |p| p && !p.accepted? } # if they don't exist, the presence validation will handle it
      errors.add(:projects, :must_have_been_accepted)
    end
  end

  def only_one_application_draft_allowed
    unless team.application_drafts.where(season: season).none?
      errors.add(:base, :Only_one_application_may_be_lodged)
    end
  end
```

> def different_projects_required
    if project1 && project1 == project2
      errors.add(:projects, :must_not_be_selected_twice)
    end
  end


```javascript 
 errors:
        models:
          application_draft:
                  attributes:
                      projects:
                          must_not_be_selected_twice: must not be selected twice
```
is this the right approach?

**Comment by F3PiX** [comment]
This is a great start, yes! 
1) The general idea is correct: the original string value becomes the value for the error key. ('must not be selected twice'). I assume the last code block you showed ^ is in the en.yml file. Right? It should be.

2) It is not required per se that the whole sentence becomes the key; main goal is that it is very clear (for your fellow developers) what error message is generated. That is partly a matter of opinion, but generally they can be more concise than the message for the user. I myself like it when the describe the error. For instance, 'must not be selected twice' can be called 'multiple_selection_error'   

3) I did not yet check the exact place in the en.yml file. One way to check that yourself is update the test files (with these new error keys') and then run the tests. If you happen to add a error to the wrong place, the tests will fail. (For example, for the Application Draft: some are going to :base, others to :projects.) The tests will tell you!

4) Minor detail: be sure to use lowercase only for the keys. (not `:Only_one_application... ` , in the third method in your question ^)   

Okay?

**Comment by nileshgulia1** [comment]
@F3PiX  Great,Thank you :)

**Comment by nileshgulia1** [comment]
@F3PiX  Need help! can you tell me how to remove these duplications:
``` yaml
 errors:
        models:
         application_draft:
                  attributes:
                      projects:
                          multiple_sel_error: must not be selected twice

    errors:                      
        models:
          application_draft:
                  attributes:
                      projects:
                          must_accepted: must have been accepted

     errors:                      
        models:
          application_draft:
                  attributes:
                          base:
                            one_app_allowed: Only one application may be lodged
```
I got this error :```Message: Request textDocument/formatting failed with message: duplicated mapping key at line 93, column -188:
        errors:
         ^```
and some indentation error also.
